name: build docker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push server-a image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/server-a ./backend/server-a
        working-directory: .
      
      - name: Build and push server-b image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/server-b ./backend/server-b
        working-directory: .
      
      - name: Build and push frontend image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend .
        working-directory: .

      - name: Build and push database image
        run: |
            docker pull postgres:latest
            docker tag postgres:latest ${{ secrets.DOCKER_USERNAME }}/database:latest
        working-directory: .
      
      - name: Deploy with Docker Compose
        run: |
          docker-compose -f docker-compose.yml up -d
